### ISSUE TITLE
Declaring the prisma client inside the db package

### ISSUE THREAD

**Issue by keepri** [nramkissoon/NPM-TurboRepo-tRPC-Next.js-NextAuth-Prisma-PlanetScale-Starter#2]
Hello,

I've been trying to generate and initialize the prisma client in the same repo internal package, but when I'm trying to import the client inside of a project I get an error.

What I'm doing different from this repo is that I'm using prisma generate with an "output" field set inside of the datasource schema config and importing from that generated client in order to initialize and export. The problem is that when I'm importing from another project in the monorepo I get that error that I was talking about that says it can't find the schema.prisma file inside of ".next/cache/...".

Any ideas? 🤞

Later edit: I managed to make it work using this repo's approach and compiling the db package using tsc. Weirdly enough this made it work. I'm wondering why did it not work when I used the next-transpile-modules instead... 🤔

**Comment by nramkissoon** [comment]
Hi,

I'm not sure I fully understand the issue here and can't give much a response without more specific details.

FYI, This repo is probably a better example of using Prisma with Turborepo at this time https://github.com/t3-oss/create-t3-turbo. It is better maintained and up to date.

Closing this since you mentioned you got it working.
